# From image for Linux OS
FROM mongo:4.0.7-xenial
# Add maintainer contact information
MAINTAINER inti luna <inti.luna.aviles@gmail.com>
# Add label
LABEL project="1_Docker_Kubernetes"
# Default command to run MongoDB
CMD ["mongod"]
