apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: proyecto1
spec:
  type: ClusterIP
  selector:
    component: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
