apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-persistent-volume
  namespace: proyecto1
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"