apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: proyecto1
type: Opaque
data:
  username: YWRtaW4=  # Valor codificado en base64 para el usuario "admin"
  password: YWRtaW5wdw==  # Valor codificado en base64 para la contraseña "adminpw"

