apiVersion: v1
kind: Service
metadata:
  name: netapi-service-v1
  namespace: proyecto1
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 7007
      targetPort: 7007
  selector:
    component: netapi-v1