apiVersion: v1
kind: Service
metadata:
  name: netapi-service-v2
  namespace: proyecto1
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 7010
      targetPort: 7010
  selector:
    component: netapi-v2
