# ---
# apiVersion: v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netapi-deployment-v1
  namespace: proyecto1
spec:
  replicas: 2
  selector:
    matchLabels:
      component: netapi-v1
  template:
    metadata:
      name: proyecto1_Inti_Luna
      labels:
        component: netapi-v1
    spec:
      containers:
        - name: netapi-v1
          image: lunadocker0198/imagenet:1.0
          ports:
            - containerPort: 7007
          env:
            - name: Entorno
              value: inti_luna
            - name: MONGO_INITDB_DATABASE
              value: test
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom: 
                secretKeyRef:
                  name: my-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:   
                secretKeyRef:
                  name: my-secret
                  key: password
            - name: CONFIG_MONGODB_URL
              #value: "mongodb://mongo:27017"
              value: "mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@mongo-service:27017/"

          resources: {}

      dnsPolicy: ClusterFirst
      restartPolicy: Always
