version: "3.8"

services:
  mongo:
    image: lunadocker0198/mongodhackinti:1.0
    #image: mongo:4.0.7-xenial
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - mongoconfig:/data/configdb
    environment:
      - Entorno=inti_luna
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpw
      - MONGO_INITDB_DATABASE=test
    command: mongod


  netapiv1:
    image: lunadocker0198/imagenet:1.0
    ports:
      - "7007:7007"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '2'
          memory: 512M
    volumes:
      - mongodata:/data/db
      - mongoconfig:/data/configdb
    environment:
      - Entorno=inti_luna
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpw
      - CONFIG_MONGODB_URL=mongodb://admin:adminpw@mongo:27017/
    depends_on:
    - mongo

  netapiv2:
    image: lunadocker0198/imagenet:2.0
    ports:
      - "7010:7010"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '2'
          memory: 512M
    volumes:
      - mongodata:/data/db
      - mongoconfig:/data/configdb
    environment:
      - Entorno=inti_luna
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpw
      - CONFIG_MONGODB_URL=mongodb://admin:adminpw@mongo:27017/
    depends_on:
    - mongo


volumes:
  mongodata:
  mongoconfig:
